from ..admin import PolymorphicParentModelAdmin as PolymorphicParentModelAdmin
from _typeshed import Incomplete
from django.contrib import admin
from polymorphic.utils import get_base_polymorphic_model as get_base_polymorphic_model

class ParentAdminNotRegistered(RuntimeError): ...

class PolymorphicChildModelAdmin(admin.ModelAdmin):
    base_model: Incomplete
    base_form: Incomplete
    base_fieldsets: Incomplete
    extra_fieldset_title: Incomplete
    show_in_index: bool
    def __init__(self, model, admin_site, *args, **kwargs) -> None: ...
    def get_form(self, request, obj=None, **kwargs): ...
    def get_model_perms(self, request): ...
    @property
    def change_form_template(self): ...
    @property
    def delete_confirmation_template(self): ...
    @property
    def object_history_template(self): ...
    def response_post_save_add(self, request, obj): ...
    def response_post_save_change(self, request, obj): ...
    def render_change_form(self, request, context, add: bool = False, change: bool = False, form_url: str = '', obj=None): ...
    def delete_view(self, request, object_id, context=None): ...
    def history_view(self, request, object_id, extra_context=None): ...
    def get_base_fieldsets(self, request, obj=None): ...
    def get_fieldsets(self, request, obj=None): ...
    def get_subclass_fields(self, request, obj=None): ...
