from _typeshed import Incomplete
from django.contrib.admin.helpers import InlineAdminForm, InlineAdminFormSet
from polymorphic.formsets import BasePolymorphicModelFormSet as BasePolymorphicModelFormSet

class PolymorphicInlineAdminForm(InlineAdminForm):
    def polymorphic_ctype_field(self): ...
    @property
    def is_empty(self): ...

class PolymorphicInlineAdminFormSet(InlineAdminFormSet):
    request: Incomplete
    obj: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self): ...
    def get_child_fieldsets(self, child_inline): ...
    def get_child_readonly_fields(self, child_inline): ...
    def get_child_prepopulated_fields(self, child_inline): ...
    def inline_formset_data(self): ...

class PolymorphicInlineSupportMixin:
    def get_inline_formsets(self, request, formsets, inline_instances, obj=None, *args, **kwargs): ...
