from _typeshed import Incomplete
from django.contrib.admin.options import InlineModelAdmin

from polymorphic.formsets import BasePolymorphicInlineFormSet as BasePolymorphicInlineFormSet
from polymorphic.formsets import PolymorphicFormSetChild as PolymorphicFormSetChild
from polymorphic.formsets import UnsupportedChildType as UnsupportedChildType
from polymorphic.formsets import polymorphic_child_forms_factory as polymorphic_child_forms_factory
from polymorphic.formsets.utils import add_media as add_media

from .helpers import PolymorphicInlineSupportMixin as PolymorphicInlineSupportMixin

class PolymorphicInlineModelAdmin(InlineModelAdmin):
    formset = BasePolymorphicInlineFormSet
    polymorphic_media: Incomplete
    extra: int
    child_inlines: Incomplete
    child_inline_instances: Incomplete
    def __init__(self, parent_model, admin_site) -> None: ...
    def get_child_inlines(self): ...
    def get_child_inline_instances(self): ...
    def get_child_inline_instance(self, model): ...
    def get_formset(self, request, obj=None, **kwargs): ...
    def get_formset_children(self, request, obj=None): ...
    def get_fieldsets(self, request, obj=None): ...
    def get_fields(self, request, obj=None): ...
    @property
    def media(self): ...
    class Child(InlineModelAdmin):
        formset_child = PolymorphicFormSetChild
        extra: int
        parent_inline: Incomplete
        def __init__(self, parent_inline) -> None: ...
        def get_formset(self, request, obj=None, **kwargs) -> None: ...
        def get_fields(self, request, obj=None): ...
        def get_formset_child(self, request, obj=None, **kwargs): ...

class StackedPolymorphicInline(PolymorphicInlineModelAdmin):
    template: str
