from typing import Any, Sequence

from django.contrib import admin
from django.db.models import Model
from django.db.models.query import QuerySet
from django.forms import ModelForm
from django.http import HttpResponse
from django_stubs_ext.http import HttpRequest

from polymorphic.utils import get_base_polymorphic_model as get_base_polymorphic_model

from .forms import PolymorphicModelChoiceForm as PolymorphicModelChoiceForm

class RegistrationClosed(RuntimeError): ...
class ChildAdminNotRegistered(RuntimeError): ...

class PolymorphicParentModelAdmin(admin.ModelAdmin):
    base_model: type[Model] | None
    child_models: Sequence[type[Model]] | None
    polymorphic_list: bool
    add_type_template: str | None
    add_type_form: type[ModelForm]
    pk_regex: str
    def __init__(self, model: type[Model], admin_site: Any, *args: Any, **kwargs: Any) -> None: ...
    def register_child(self, model: type[Model], model_admin: type[admin.ModelAdmin]) -> None: ...
    def get_child_models(self) -> Sequence[type[Model]]: ...
    def get_child_type_choices(
        self, request: HttpRequest, action: str
    ) -> list[tuple[str, str]]: ...
    def get_queryset(self, request: HttpRequest) -> QuerySet: ...
    def add_view(
        self, request: HttpRequest, form_url: str = "", extra_context: Any = None
    ) -> HttpResponse: ...
    def change_view(
        self, request: HttpRequest, object_id: str, *args: Any, **kwargs: Any
    ) -> HttpResponse: ...
    def changeform_view(
        self,
        request: HttpRequest,
        object_id: str | None = None,
        *args: Any,
        **kwargs: Any,
    ) -> HttpResponse: ...
    def history_view(
        self, request: HttpRequest, object_id: str, extra_context: Any = None
    ) -> HttpResponse: ...
    def delete_view(
        self, request: HttpRequest, object_id: str, extra_context: Any = None
    ) -> HttpResponse: ...
    def get_preserved_filters(self, request: HttpRequest) -> str: ...
    def get_urls(self) -> list[Any]: ...
    def subclass_view(self, request: HttpRequest, path: str) -> HttpResponse: ...
    def add_type_view(self, request: HttpRequest, form_url: str = "") -> HttpResponse: ...
    def render_add_type_form(
        self, request: HttpRequest, context: Any, form_url: str = ""
    ) -> HttpResponse: ...
    @property
    def change_list_template(self) -> str: ...
