from _typeshed import Incomplete
from django.contrib import admin

from polymorphic.utils import get_base_polymorphic_model as get_base_polymorphic_model

from .forms import PolymorphicModelChoiceForm as PolymorphicModelChoiceForm

class RegistrationClosed(RuntimeError): ...
class ChildAdminNotRegistered(RuntimeError): ...

class PolymorphicParentModelAdmin(admin.ModelAdmin):
    base_model: Incomplete
    child_models: Incomplete
    polymorphic_list: bool
    add_type_template: Incomplete
    add_type_form = PolymorphicModelChoiceForm
    pk_regex: str
    def __init__(self, model, admin_site, *args, **kwargs) -> None: ...
    def register_child(self, model, model_admin) -> None: ...
    def get_child_models(self): ...
    def get_child_type_choices(self, request, action): ...
    def get_queryset(self, request): ...
    def add_view(self, request, form_url: str = "", extra_context=None): ...
    def change_view(self, request, object_id, *args, **kwargs): ...
    def changeform_view(self, request, object_id=None, *args, **kwargs): ...
    def history_view(self, request, object_id, extra_context=None): ...
    def delete_view(self, request, object_id, extra_context=None): ...
    def get_preserved_filters(self, request): ...
    def get_urls(self): ...
    def subclass_view(self, request, path): ...
    def add_type_view(self, request, form_url: str = ""): ...
    def render_add_type_form(self, request, context, form_url: str = ""): ...
    @property
    def change_list_template(self): ...
