# Generated by Django 4.2 on 2026-01-09 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogOne',
            fields=[
                ('blogbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drf.blogbase')),
                ('info', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('drf.blogbase',),
        ),
        migrations.CreateModel(
            name='BlogTwo',
            fields=[
                ('blogbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drf.blogbase')),
            ],
            options={
                'abstract': False,
            },
            bases=('drf.blogbase',),
        ),
        migrations.CreateModel(
            name='BlogThree',
            fields=[
                ('blogbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drf.blogbase')),
                ('info', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('info', 'about')},
            },
            bases=('drf.blogbase',),
        ),
    ]
