# Generated by Django 4.2.15 on 2024-08-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueHeadDuck',
            fields=[
                ('duck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.duck')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tests.duck',),
        ),
        migrations.CreateModel(
            name='PurpleHeadDuck',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tests.blueheadduck',),
        ),
    ]
