# Generated by Django 2.1.9 on 2019-06-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DucksLake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LakeWithThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='duck',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='lakewiththrough',
            name='ducks',
            field=models.ManyToManyField(through='tests.DucksLake', to='tests.Duck'),
        ),
        migrations.AddField(
            model_name='lake',
            name='ducks',
            field=models.ManyToManyField(to='tests.Duck'),
        ),
        migrations.AddField(
            model_name='duckslake',
            name='duck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Duck'),
        ),
        migrations.AddField(
            model_name='duckslake',
            name='lake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.LakeWithThrough'),
        ),
    ]
