# Generated by Django 4.2 on 2026-02-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child1',
            fields=[
                ('parentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='type_hints_one2one.parentmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('type_hints_one2one.parentmodel',),
        ),
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_forward', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='type_hints_one2one.parentmodel')),
            ],
        ),
        migrations.AddField(
            model_name='parentmodel',
            name='related_forward',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_reverse', to='type_hints_one2one.relatedmodel'),
        ),
        migrations.CreateModel(
            name='Child2',
            fields=[
                ('child1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='type_hints_one2one.child1')),
            ],
            options={
                'abstract': False,
            },
            bases=('type_hints_one2one.child1',),
        ),
    ]
