from _typeshed import Incomplete
from django.test import TestCase
from django.urls import include as include

class AdminTestCase(TestCase):
    model: Incomplete
    admin_class: Incomplete
    @classmethod
    def setUpClass(cls) -> None: ...
    admin_site: Incomplete
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def register(self, model): ...
    def admin_register(self, model, admin_site) -> None: ...
    def get_admin_instance(self, model): ...
    @classmethod
    def tearDownClass(cls) -> None: ...
    def get_add_url(self, model): ...
    def get_changelist_url(self, model): ...
    def get_change_url(self, model, object_id): ...
    def get_history_url(self, model, object_id): ...
    def get_delete_url(self, model, object_id): ...
    def admin_get_add(self, model, qs: str = ''): ...
    def admin_post_add(self, model, formdata, qs: str = ''): ...
    def admin_get_changelist(self, model): ...
    def admin_get_change(self, model, object_id, query=None, **extra): ...
    def admin_post_change(self, model, object_id, formdata, **extra): ...
    def admin_get_history(self, model, object_id, query=None, **extra): ...
    def admin_get_delete(self, model, object_id, query=None, **extra): ...
    def admin_post_delete(self, model, object_id, **extra): ...
    def create_admin_request(self, method, url, data=None, **extra): ...
    def assertFormSuccess(self, request_url, response) -> None: ...
