from django.test import TransactionTestCase
from polymorphic.models import PolymorphicModel as PolymorphicModel, PolymorphicTypeUndefined as PolymorphicTypeUndefined
from polymorphic.tests.models import Enhance_Base as Enhance_Base, Enhance_Inherit as Enhance_Inherit, Model2A as Model2A, Model2B as Model2B, Model2C as Model2C, Model2D as Model2D
from polymorphic.utils import get_base_polymorphic_model as get_base_polymorphic_model, reset_polymorphic_ctype as reset_polymorphic_ctype, sort_by_subclass as sort_by_subclass

class UtilsTests(TransactionTestCase):
    def test_sort_by_subclass(self) -> None: ...
    def test_reset_polymorphic_ctype(self): ...
    def test_get_base_polymorphic_model(self) -> None: ...
    def test_get_base_polymorphic_model_skip_abstract(self) -> None: ...
