from django.test import TransactionTestCase
from polymorphic import query_translate as query_translate
from polymorphic.managers import PolymorphicManager as PolymorphicManager
from polymorphic.models import PolymorphicTypeInvalid as PolymorphicTypeInvalid, PolymorphicTypeUndefined as PolymorphicTypeUndefined
from polymorphic.tests.models import Account as Account, ArtProject as ArtProject, Base as Base, BlogA as BlogA, BlogB as BlogB, BlogBase as BlogBase, BlogEntry as BlogEntry, BlogEntry_limit_choices_to as BlogEntry_limit_choices_to, ChildModelWithManager as ChildModelWithManager, CustomPkBase as CustomPkBase, CustomPkInherit as CustomPkInherit, Duck as Duck, Enhance_Base as Enhance_Base, Enhance_Inherit as Enhance_Inherit, Enhance_Plain as Enhance_Plain, InitTestModelSubclass as InitTestModelSubclass, InlineModelA as InlineModelA, InlineModelB as InlineModelB, InlineParent as InlineParent, MRODerived as MRODerived, Model2A as Model2A, Model2B as Model2B, Model2C as Model2C, Model2D as Model2D, ModelExtraA as ModelExtraA, ModelExtraB as ModelExtraB, ModelExtraC as ModelExtraC, ModelExtraExternal as ModelExtraExternal, ModelFieldNameTest as ModelFieldNameTest, ModelOrderLine as ModelOrderLine, ModelShow1 as ModelShow1, ModelShow1_plain as ModelShow1_plain, ModelShow2 as ModelShow2, ModelShow2_plain as ModelShow2_plain, ModelShow3 as ModelShow3, ModelUnderRelChild as ModelUnderRelChild, ModelUnderRelParent as ModelUnderRelParent, ModelWithMyManager as ModelWithMyManager, ModelWithMyManager2 as ModelWithMyManager2, ModelWithMyManagerDefault as ModelWithMyManagerDefault, ModelWithMyManagerNoDefault as ModelWithMyManagerNoDefault, ModelX as ModelX, ModelY as ModelY, MultiTableDerived as MultiTableDerived, MyManager as MyManager, MyManagerQuerySet as MyManagerQuerySet, NonPolymorphicParent as NonPolymorphicParent, NonProxyChild as NonProxyChild, One2OneRelatingModel as One2OneRelatingModel, One2OneRelatingModelDerived as One2OneRelatingModelDerived, ParentLinkAndRelatedName as ParentLinkAndRelatedName, ParentModelWithManager as ParentModelWithManager, PlainA as PlainA, PlainB as PlainB, PlainC as PlainC, PlainChildModelWithManager as PlainChildModelWithManager, PlainMyManager as PlainMyManager, PlainMyManagerQuerySet as PlainMyManagerQuerySet, PlainParentModelWithManager as PlainParentModelWithManager, ProxiedBase as ProxiedBase, ProxyBase as ProxyBase, ProxyChild as ProxyChild, ProxyModelA as ProxyModelA, ProxyModelB as ProxyModelB, ProxyModelBase as ProxyModelBase, PurpleHeadDuck as PurpleHeadDuck, RedheadDuck as RedheadDuck, RelatingModel as RelatingModel, RelationA as RelationA, RelationB as RelationB, RelationBC as RelationBC, RelationBase as RelationBase, RubberDuck as RubberDuck, SpecialAccount1 as SpecialAccount1, SpecialAccount1_1 as SpecialAccount1_1, SpecialAccount2 as SpecialAccount2, SubclassSelectorAbstractBaseModel as SubclassSelectorAbstractBaseModel, SubclassSelectorAbstractConcreteModel as SubclassSelectorAbstractConcreteModel, SubclassSelectorProxyBaseModel as SubclassSelectorProxyBaseModel, SubclassSelectorProxyConcreteModel as SubclassSelectorProxyConcreteModel, UUIDArtProject as UUIDArtProject, UUIDArtProjectA as UUIDArtProjectA, UUIDArtProjectB as UUIDArtProjectB, UUIDArtProjectC as UUIDArtProjectC, UUIDArtProjectD as UUIDArtProjectD, UUIDPlainA as UUIDPlainA, UUIDPlainB as UUIDPlainB, UUIDPlainC as UUIDPlainC, UUIDProject as UUIDProject, UUIDResearchProject as UUIDResearchProject

class PolymorphicTests(TransactionTestCase):
    def test_annotate_aggregate_order(self) -> None: ...
    def test_limit_choices_to(self) -> None: ...
    def test_primary_key_custom_field_problem(self) -> None: ...
    def create_model2abcd(self): ...
    def test_simple_inheritance(self): ...
    def test_defer_fields(self) -> None: ...
    def test_defer_related_fields(self) -> None: ...
    def test_manual_get_real_instance(self) -> None: ...
    def test_get_real_instance_with_stale_content_type(self) -> None: ...
    def test_non_polymorphic(self): ...
    def test_get_real_instances(self): ...
    def test_queryset_missing_derived(self) -> None: ...
    def test_queryset_missing_contenttype(self) -> None: ...
    def test_translate_polymorphic_q_object(self): ...
    def test_create_instanceof_q(self) -> None: ...
    def test_base_manager(self): ...
    def test_instance_default_manager(self): ...
    def test_foreignkey_field(self) -> None: ...
    def test_onetoone_field(self) -> None: ...
    def test_manytomany_field(self): ...
    def test_extra_method(self): ...
    def test_instance_of_filter(self): ...
    def test_polymorphic___filter(self): ...
    def test_polymorphic_applabel___filter(self): ...
    def test_query_filter_exclude_is_immutable(self) -> None: ...
    def test_polymorphic___filter_field(self) -> None: ...
    def test_polymorphic___filter_reverse_field(self) -> None: ...
    def test_delete(self): ...
    def test_combine_querysets(self) -> None: ...
    def test_multiple_inheritance(self) -> None: ...
    def test_relation_base(self) -> None: ...
    def test_user_defined_manager(self): ...
    def test_user_defined_manager_as_secondary(self): ...
    def test_user_objects_manager_as_secondary(self) -> None: ...
    def test_user_defined_queryset_as_manager(self): ...
    def test_manager_inheritance(self) -> None: ...
    def test_queryset_assignment(self) -> None: ...
    def test_proxy_models(self) -> None: ...
    def test_queryset_on_proxy_model_does_not_return_superclasses(self) -> None: ...
    def test_proxy_get_real_instance_class(self) -> None: ...
    def test_content_types_for_proxy_models(self) -> None: ...
    def test_proxy_model_inheritance(self) -> None: ...
    def test_custom_pk(self) -> None: ...
    def test_fix_getattribute(self) -> None: ...
    def test_parent_link_and_related_name(self) -> None: ...
    def test_polymorphic__accessor_caching(self) -> None: ...
    def test_polymorphic__aggregate(self) -> None: ...
    def test_polymorphic__aggregate_empty_queryset(self) -> None: ...
    def test_polymorphic__complex_aggregate(self): ...
    def test_polymorphic__filtered_relation(self) -> None: ...
    def test_polymorphic__expressions(self) -> None: ...
    def test_null_polymorphic_id(self) -> None: ...
    def test_invalid_polymorphic_id(self) -> None: ...
    def test_bulk_create_abstract_inheritance(self) -> None: ...
    def test_bulk_create_proxy_inheritance(self) -> None: ...
    def test_bulk_create_unsupported_multi_table_inheritance(self) -> None: ...
    def test_bulk_create_ignore_conflicts(self) -> None: ...
    def test_bulk_create_no_ignore_conflicts(self) -> None: ...
    def test_can_query_using_subclass_selector_on_abstract_model(self) -> None: ...
    def test_can_query_using_subclass_selector_on_proxy_model(self) -> None: ...
    def test_prefetch_related_behaves_normally_with_polymorphic_model(self) -> None: ...
    def test_prefetch_related_with_missing(self) -> None: ...
    def test_refresh_from_db_fields(self) -> None: ...
    def test_non_polymorphic_parent(self) -> None: ...
    def test_iteration(self) -> None: ...
    def test_transmogrify_with_init(self) -> None: ...
    def test_subqueries(self) -> None: ...
    def test_one_to_one_primary_key(self) -> None: ...
    def test_manager_override(self) -> None: ...
    def test_abstract_managers(self) -> None: ...
    def test_fk_polymorphism(self) -> None: ...
    def test_polymorphic_extension(self) -> None: ...
    def test_manytomany_without_through_field(self) -> None: ...
    def test_manytomany_with_through_field(self) -> None: ...
    def test_create_from_super(self) -> None: ...
    def test_through_models_creates_and_reads(self) -> None: ...
    def test_through_model_updates(self) -> None: ...
