from _typeshed import Incomplete
from django.test import TestCase
from polymorphic.tests.models import Base as Base, BlogA as BlogA, BlogEntry as BlogEntry, Model2A as Model2A, Model2B as Model2B, Model2C as Model2C, Model2D as Model2D, ModelX as ModelX, ModelY as ModelY, One2OneRelatingModel as One2OneRelatingModel, RelatingModel as RelatingModel, RelationA as RelationA, RelationB as RelationB, RelationBase as RelationBase

class MultipleDatabasesTests(TestCase):
    databases: Incomplete
    def test_save_to_non_default_database(self): ...
    def test_instance_of_filter_on_non_default_database(self): ...
    def test_forward_many_to_one_descriptor_on_non_default_database(self) -> None: ...
    def test_reverse_many_to_one_descriptor_on_non_default_database(self) -> None: ...
    def test_reverse_one_to_one_descriptor_on_non_default_database(self) -> None: ...
    def test_many_to_many_descriptor_on_non_default_database(self) -> None: ...
    def test_deletion_cascade_on_non_default_db(self) -> None: ...
    def test_create_from_super(self) -> None: ...
