from typing import Any, TypeVar

from django_stubs.db.models import Manager, Model
from django_stubs.query import QuerySet

from polymorphic.query import PolymorphicQuerySet

_M = TypeVar("_M", bound=Model)

class PolymorphicManager(Manager[_M]):
    queryset_class: type[PolymorphicQuerySet[_M]]
    @classmethod
    def from_queryset(
        cls, queryset_class: type[QuerySet], class_name: str | None = None
    ) -> Any: ...
    def get_queryset(self) -> PolymorphicQuerySet[_M]: ...
    def non_polymorphic(self) -> PolymorphicQuerySet[_M]: ...
    def instance_of(self, *args: type[Model]) -> PolymorphicQuerySet[_M]: ...
    def not_instance_of(self, *args: type[Model]) -> PolymorphicQuerySet[_M]: ...
    def get_real_instances(self, base_result_objects: Any = None) -> list[_M]: ...
    def create_from_super(self, obj: Model, **kwargs: Any) -> _M: ...
