from django.db import models

from polymorphic.query import PolymorphicQuerySet as PolymorphicQuerySet

__all__ = list[str]

class PolymorphicManager(models.Manager):
    queryset_class = PolymorphicQuerySet
    @classmethod
    def from_queryset(
        cls, queryset_class: type[PolymorphicQuerySet], class_name: str | None = None
    ): ...
    def get_queryset(self): ...
    def non_polymorphic(self): ...
    def instance_of(self, *args): ...
    def not_instance_of(self, *args): ...
    def get_real_instances(self, base_result_objects=None): ...
    def create_from_super(self, obj, **kwargs): ...
