from typing import Any, TypeVar

from django.db import models

from polymorphic.query import PolymorphicQuerySet

_M = TypeVar("_M", bound=models.Model)

class PolymorphicManager(models.Manager[_M]):
    queryset_class: type[PolymorphicQuerySet[_M]]
    @classmethod
    def from_queryset(
        cls, queryset_class: type[models.QuerySet], class_name: str | None = None
    ) -> Any: ...
    def get_queryset(self) -> PolymorphicQuerySet[_M]: ...
    def non_polymorphic(self) -> PolymorphicQuerySet[_M]: ...
    def instance_of(self, *args: type[models.Model]) -> PolymorphicQuerySet[_M]: ...
    def not_instance_of(self, *args: type[models.Model]) -> PolymorphicQuerySet[_M]: ...
    def get_real_instances(self, base_result_objects: Any = None) -> list[_M]: ...
    def create_from_super(self, obj: models.Model, **kwargs: Any) -> _M: ...
