from typing import Any

from django.contrib.contenttypes.models import ContentType
from django.db import models

from .base import PolymorphicModelBase as PolymorphicModelBase
from .managers import PolymorphicManager as PolymorphicManager

class PolymorphicTypeUndefined(LookupError): ...
class PolymorphicTypeInvalid(RuntimeError): ...

class PolymorphicModel(models.Model, metaclass=PolymorphicModelBase):
    polymorphic_model_marker: bool
    polymorphic_query_multiline_output: bool
    polymorphic_ctype: models.ForeignKey[ContentType]
    polymorphic_internal_model_fields: list[str]
    objects: PolymorphicManager[Any]
    class Meta:
        abstract: bool
        base_manager_name: str

    @classmethod
    def translate_polymorphic_Q_object(cls, q: models.Q) -> models.Q: ...
    def pre_save_polymorphic(self, using: str = ...) -> None: ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
    def get_real_instance_class(self) -> type[PolymorphicModel] | None: ...
    def get_real_concrete_instance_class_id(self) -> int | None: ...
    def get_real_concrete_instance_class(self) -> type[PolymorphicModel] | None: ...
    def get_real_instance(self) -> PolymorphicModel: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
