from typing import Any, Iterator, TypeVar

from django.db.models import Model
from django_stubs.query import ModelIterable, QuerySet

from .query_translate import translate_polymorphic_field_path as translate_polymorphic_field_path
from .query_translate import (
    translate_polymorphic_filter_definitions_in_args as translate_polymorphic_filter_definitions_in_args,
)
from .query_translate import (
    translate_polymorphic_filter_definitions_in_kwargs as translate_polymorphic_filter_definitions_in_kwargs,
)
from .query_translate import translate_polymorphic_Q_object as translate_polymorphic_Q_object

Polymorphic_QuerySet_objects_per_request: int

_M = TypeVar("_M", bound=Model)

class PolymorphicModelIterable(ModelIterable):
    def __iter__(self) -> Iterator[Any]: ...

def transmogrify(cls: type[_M], obj: Any) -> _M: ...

class PolymorphicQuerySet(QuerySet[_M]):
    polymorphic_disabled: bool
    polymorphic_deferred_loading: tuple[set[str], bool]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def as_manager(cls) -> Any: ...
    def bulk_create(
        self, objs: Any, batch_size: int | None = None, ignore_conflicts: bool = False
    ) -> list[_M]: ...
    def non_polymorphic(self) -> PolymorphicQuerySet[_M]: ...
    def instance_of(self, *args: type[Model]) -> PolymorphicQuerySet[_M]: ...
    def not_instance_of(self, *args: type[Model]) -> PolymorphicQuerySet[_M]: ...
    def order_by(self, *field_names: Any) -> PolymorphicQuerySet[_M]: ...
    def defer(self, *fields: Any) -> PolymorphicQuerySet[_M]: ...
    def only(self, *fields: Any) -> PolymorphicQuerySet[_M]: ...
    def annotate(self, *args: Any, **kwargs: Any) -> PolymorphicQuerySet[_M]: ...
    def aggregate(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    class _p_list_class(list[Any]): ...

    def get_real_instances(self, base_result_objects: Any = None) -> list[_M]: ...
