from django.db.models.query import ModelIterable, QuerySet

from .query_translate import translate_polymorphic_field_path as translate_polymorphic_field_path
from .query_translate import (
    translate_polymorphic_filter_definitions_in_args as translate_polymorphic_filter_definitions_in_args,
)
from .query_translate import (
    translate_polymorphic_filter_definitions_in_kwargs as translate_polymorphic_filter_definitions_in_kwargs,
)
from .query_translate import translate_polymorphic_Q_object as translate_polymorphic_Q_object

Polymorphic_QuerySet_objects_per_request: int

class PolymorphicModelIterable(ModelIterable):
    def __iter__(self): ...

def transmogrify(cls, obj): ...

class PolymorphicQuerySet(QuerySet):
    polymorphic_disabled: bool
    polymorphic_deferred_loading: tuple[set, bool]
    def __init__(self, *args, **kwargs) -> None: ...
    def as_manager(cls): ...
    def bulk_create(self, objs, batch_size=None, ignore_conflicts: bool = False): ...
    def non_polymorphic(self): ...
    def instance_of(self, *args): ...
    def not_instance_of(self, *args): ...
    def order_by(self, *field_names): ...
    def defer(self, *fields): ...
    def only(self, *fields): ...
    def annotate(self, *args, **kwargs): ...
    def aggregate(self, *args, **kwargs): ...
    class _p_list_class(list): ...

    def get_real_instances(self, base_result_objects=None): ...
