from typing import Any, Iterable

from django.db import models
from django.db.models import Model

def translate_polymorphic_filter_definitions_in_kwargs(
    queryset_model: type[Model], kwargs: dict[str, Any], using: str = ...
) -> list[models.Q]: ...
def translate_polymorphic_Q_object(
    queryset_model: type[Model], potential_q_object: models.Q, using: str = ...
) -> models.Q: ...
def translate_polymorphic_filter_definitions_in_args(
    queryset_model: type[Model], args: Iterable[Any], using: str = ...
) -> list[models.Q]: ...
def translate_polymorphic_field_path(queryset_model: type[Model], field_path: str) -> str: ...
def create_instanceof_q(
    modellist: Iterable[type[Model]] | type[Model],
    not_instance_of: bool = False,
    using: str = ...,
) -> models.Q | None: ...
