from polymorphic.base import PolymorphicModelBase as PolymorphicModelBase
from polymorphic.models import PolymorphicModel as PolymorphicModel

def reset_polymorphic_ctype(*models, **filters) -> None: ...
def sort_by_subclass(*classes): ...
def get_base_polymorphic_model(ChildModel, allow_abstract: bool = False): ...
