# Generated by Django 4.2 on 2026-02-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaOutlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('articles', models.ManyToManyField(related_name='topics', to='type_hints.article')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='type_hints.article')),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('type_hints.article',),
        ),
        migrations.CreateModel(
            name='EditorialTopic',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='type_hints.topic')),
                ('editor', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('type_hints.topic',),
        ),
        migrations.CreateModel(
            name='LocationTopic',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='type_hints.topic')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('type_hints.topic',),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='type_hints.article')),
                ('source', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('type_hints.article',),
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('mediaoutlet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='type_hints.mediaoutlet')),
                ('service_area', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('type_hints.mediaoutlet',),
        ),
        migrations.CreateModel(
            name='OnlineBlog',
            fields=[
                ('mediaoutlet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='type_hints.mediaoutlet')),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('type_hints.mediaoutlet',),
        ),
        migrations.AddField(
            model_name='article',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='type_hints.mediaoutlet'),
        ),
        migrations.AddField(
            model_name='article',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
