__version__ = '0.1.3'
__title__ = 'django-rest-polymorphic'
__description__ = 'Polymorphic serializers for Django REST Framework.'
__url__ = 'https://github.com/apirobot/django-rest-polymorphic'
__author__ = 'Denis Orehovsky'
__author_email__ = 'denis.orehovsky@gmail.com'
__license__ = 'MIT License'
