# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-24 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pexp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelc',
            name='field4',
            field=models.ManyToManyField(related_name='related_c', to='pexp.ModelB'),
        ),
    ]
