name: Bandit

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - "src/**"
      - "pyproject.toml"
      - "justfile"
      - ".github/workflows/bandit.yml"
  workflow_dispatch:

permissions:
  contents: read
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bandit-analysis:
    name: Run Bandit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        id: sp
        with:
          python-version: '3.x'
          allow-prereleases: true
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: false
      - name: Install Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3

      - name: Run Bandit
        run: |
          just bandit

      - name: Upload analysis results
        if: ${{ always() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: bandit-results
          path: bandit.sarif
          retention-days: 7

      - name: Upload to code-scanning
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@e46ed2cbd01164d986452f91f178727624ae40d7
        with:
          sarif_file: bandit.sarif
