name: Test

permissions:
  contents: read

on:
  push:
    tags-ignore:
      - '*'
    branches: ['main']
  pull_request:
    branches: ['main']
    paths:
      - "src/**"
      - ".github/workflows/test.yml"
      - "pyproject.toml"
      - "justfile"
  merge_group:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      debug:
        description: 'Open ssh debug session.'
        required: true
        default: false
        type: boolean
      clear_cache:
        description: 'Clear GitHub Tool cache.'
        required: true
        default: false
        type: boolean
  schedule:
    # Every Sunday at 9:00 AM Los Angeles time.
    # GitHub cron is UTC; 09:00 PT == 17:00 UTC (PST).
    - cron: '0 17 * * 0'


jobs:

  postgres:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    # Service containers to run with `container-job`
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        postgres-version: ['12', '14', 'latest']
        psycopg-version: ['psycopg2', 'psycopg3']
        django-version:
          - 'dj42' # LTS April 2026
          - 'dj52' # LTS April 2028
          - 'dj60' #
        exclude:

          - python-version: '3.10'
            django-version: 'dj60'
          - python-version: '3.11'
            django-version: 'dj60'

          - python-version: '3.13'
            django-version: 'dj42'

          - python-version: '3.14'
            django-version: 'dj42'
          - python-version: '3.14'
            django-version: 'dj52'

          - postgres-version: '12'
            django-version: 'dj52'
          - postgres-version: '12'
            django-version: 'dj60'

          - postgres-version: '14'
            django-version: 'dj42'
          - postgres-version: '14'
            django-version: 'dj52'
          - postgres-version: '14'
            django-version: 'dj60'

          - postgres-version: 'latest'
            django-version: 'dj42'

          - postgres-version: '12'
            psycopg-version: 'psycopg3'
          - postgres-version: 'latest'
            psycopg-version: 'psycopg2'

          # https://github.com/psycopg/psycopg2/pull/1695
          - python-version: '3.13'
            psycopg-version: 'psycopg2'
          - python-version: '3.14'
            psycopg-version: 'psycopg2'

    env:
      RDBMS: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      COVERAGE_FILE: linux-py${{ matrix.python-version }}-${{ matrix.django-version }}-${{ matrix.psycopg-version }}-pg${{ matrix.postgres-version }}.coverage
      TEST_PYTHON_VERSION: ${{ matrix.python-version }}
      TEST_DJANGO_VERSION: ${{ matrix.django-version }}
      TEST_DATABASE_CLIENT_VERSION: ${{ matrix.psycopg-version }}
      TEST_DATABASE_VERSION: ${{ matrix.postgres-version }}

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:${{ matrix.postgres-version }}
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - name: Clear Tool cache
      if: ${{ github.event.inputs.clear_cache == 'true' }}
      run: sudo rm -rf /opt/hostedtoolcache
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      id: sp
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Create test databases
      run: |
        psql -h localhost -p 5432 -U postgres -d postgres -c "CREATE DATABASE test1;"
        psql -h localhost -p 5432 -U postgres -d postgres -c "CREATE DATABASE test2;"
    - name: Install uv
      uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098
      with:
        enable-cache: false
    - name: Setup Just
      uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b
    - name: Install Emacs
      if: ${{ github.event.inputs.debug == 'true' }}
      run: |
        sudo apt install emacs
    - name: Setup tmate session
      if: ${{ github.event.inputs.debug == 'true' }}
      uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101
      timeout-minutes: 60
    - name: Run Unit Tests
      env:
        TEST_PYTHON: ${{ steps.sp.outputs.python-path }}
      run: |
        just test-all --group "${{ matrix.psycopg-version }}" -p "$TEST_PYTHON" --group "$TEST_DJANGO_VERSION"
    - name: Store coverage files
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      with:
        name: ${{ env.COVERAGE_FILE }}
        path: ${{ env.COVERAGE_FILE }}


  sqlite:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    env:
      RDBMS: sqlite
      COVERAGE_FILE: linux-py${{ matrix.python-version }}-${{ matrix.django-version }}-sqlite.coverage
      TEST_PYTHON_VERSION: ${{ matrix.python-version }}
      TEST_DJANGO_VERSION: ${{ matrix.django-version }}
      TEST_DATABASE_VERSION: "sqlite"
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12', '3.14']
        django-version:
          - 'dj42' # LTS April 2026
          - 'dj52' # LTS April 2028
          - 'dj60' #
        exclude:
          - python-version: '3.10'
            django-version: 'dj52'
          - python-version: '3.10'
            django-version: 'dj60'

          - python-version: '3.12'
            django-version: 'dj42'
          - python-version: '3.12'
            django-version: 'dj60'

          - python-version: '3.14'
            django-version: 'dj42'
          - python-version: '3.14'
            django-version: 'dj52'

    steps:
      - name: Clear Tool cache
        if: ${{ github.event.inputs.clear_cache == 'true' }}
        run: sudo rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        id: sp
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098
        with:
          enable-cache: false
      - name: Setup Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b
      - name: Install Emacs
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          sudo apt install emacs
      - name: Setup tmate session
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101
        timeout-minutes: 60
      - name: Run Unit Tests
        env:
          TEST_PYTHON: ${{ steps.sp.outputs.python-path }}
        run: |
          just test-all -p "$TEST_PYTHON" --group "$TEST_DJANGO_VERSION"
      - name: Store coverage files
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: ${{ env.COVERAGE_FILE }}
          path: ${{ env.COVERAGE_FILE }}


  mysql:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12', '3.14']
        mysql-version: ['8.0', 'latest']
        mysqlclient-version: ['mysqlclient14', 'mysqlclient2x']
        django-version:
          - 'dj42'    # LTS April 2024
          - 'dj52'    # LTS April 2028
          - 'dj60'    #
        exclude:
          - django-version: 'dj42'
            mysql-version: 'latest'

          - django-version: 'dj60'
            mysql-version: '8.0'

          - mysql-version: 'latest'
            mysqlclient-version: 'mysqlclient14'

          - python-version: '3.12'
            django-version: 'dj42'
          - python-version: '3.14'
            django-version: 'dj42'

          - python-version: '3.10'
            django-version: 'dj52'
          - python-version: '3.14'
            django-version: 'dj52'
          - django-version: 'dj52'
            mysqlclient-version: 'mysqlclient14'

          - python-version: '3.10'
            django-version: 'dj60'
          - python-version: '3.12'
            django-version: 'dj60'

    env:
      RDBMS: mysql
      MYSQL_VERSION: ${{ matrix.mysql-version }}
      COVERAGE_FILE: linux-py${{ matrix.python-version }}-${{ matrix.django-version }}-${{ matrix.mysqlclient-version }}-mysql${{ matrix.mysql-version }}.coverage
      TEST_PYTHON_VERSION: ${{ matrix.python-version }}
      TEST_DJANGO_VERSION: ${{ matrix.django-version }}
      TEST_DATABASE_CLIENT_VERSION: ${{ matrix.mysqlclient-version }}
      TEST_DATABASE_VERSION: ${{ matrix.mysql-version }}

    services:
      mysql:
        # Docker Hub image
        image: mysql:${{ matrix.mysql-version }}
        # Provide the password for mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_MULTIPLE_DATABASES: test1,test2
        # Set health checks to wait until mysql has started
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 3306 on service container to the host
          - 3306:3306

    steps:
      # make text comparisons case sensitive (some tests)
      - name: Set default collation for MySQL
        run: |
          mysql -h 127.0.0.1 -u root -proot <<EOF
          SET GLOBAL character_set_server='utf8mb4';
          SET GLOBAL collation_server='utf8mb4_0900_as_cs';
          EOF
      - name: Clear Tool cache
        if: ${{ github.event.inputs.clear_cache == 'true' }}
        run: sudo rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        id: sp
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install Emacs
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          sudo apt install emacs
      - name: Setup tmate session
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101
        timeout-minutes: 60
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098
        with:
          enable-cache: false
      - name: Setup Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b
      - name: Run Unit Tests
        env:
          TEST_PYTHON: ${{ steps.sp.outputs.python-path }}
        run: |
          just test-all --group "${{ matrix.mysqlclient-version }}" -p "$TEST_PYTHON" --group "$TEST_DJANGO_VERSION"
      - name: Store coverage files
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: ${{ env.COVERAGE_FILE }}
          path: ${{ env.COVERAGE_FILE }}

  mariadb:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    env:
      RDBMS: mariadb
      COVERAGE_FILE: linux-py${{ matrix.python-version }}-${{ matrix.django-version }}-${{ matrix.mysqlclient-version }}-mariadb${{ matrix.mariadb-version }}.coverage
      TEST_PYTHON_VERSION: ${{ matrix.python-version }}
      TEST_DJANGO_VERSION: ${{ matrix.django-version }}
      TEST_DATABASE_CLIENT_VERSION: ${{ matrix.mysqlclient-version }}
      TEST_DATABASE_VERSION: ${{ matrix.mariadb-version }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12', '3.14']
        mysqlclient-version: ['mysqlclient14', 'mysqlclient2x']
        mariadb-version: ['10.4', 'latest']
        mariadb-healthcheck: ["mysqladmin ping", "healthcheck.sh --connect --innodb_initialized"]
        django-version:
          - 'dj42'    # LTS April 2024
          - 'dj52'    # LTS April 2028
          - 'dj60'    #
        exclude:
          - django-version: 'dj42'
            mariadb-version: 'latest'

          - django-version: 'dj52'
            mariadb-version: '10.4'
          - django-version: 'dj60'
            mariadb-version: '10.4'

          - mariadb-version: 'latest'
            mysqlclient-version: 'mysqlclient14'

          - python-version: '3.12'
            django-version: 'dj42'
          - python-version: '3.14'
            django-version: 'dj42'

          - python-version: '3.10'
            django-version: 'dj52'
          - python-version: '3.14'
            django-version: 'dj52'
          - django-version: 'dj52'
            mysqlclient-version: 'mysqlclient14'

          - python-version: '3.10'
            django-version: 'dj60'
          - python-version: '3.12'
            django-version: 'dj60'

          - mariadb-version: '10.4'
            mysqlclient-version: 'mysqlclient2x'

          - mariadb-version: 'latest'
            mariadb-healthcheck: "mysqladmin ping"
          - mariadb-version: '10.4'
            mariadb-healthcheck: "healthcheck.sh --connect --innodb_initialized"

    services:
      mariadb:
        # Docker Hub image
        image: mariadb:${{ matrix.mariadb-version }}
        # Provide the password for mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_MULTIPLE_DATABASES: test1,test2
        # Set health checks to wait until mysql has started
        options: >-
          --health-cmd="${{ matrix.mariadb-healthcheck }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 3306 on service container to the host
          - 3306:3306

    steps:
      # make text comparisons case sensitive (some tests)
      - name: Set default collation for MariaDB
        run: |
          mysql -h 127.0.0.1 -u root -proot <<EOF
          SET GLOBAL character_set_server='utf8mb4';
          SET GLOBAL collation_server='utf8mb4_bin';
          EOF
      - name: Clear Tool cache
        if: ${{ github.event.inputs.clear_cache == 'true' }}
        run: sudo rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        id: sp
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install Emacs
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          sudo apt install emacs
      - name: Setup tmate session
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101
        timeout-minutes: 60
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098
        with:
          enable-cache: false
      - name: Setup Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b
      - name: Run Unit Tests
        env:
          TEST_PYTHON: ${{ steps.sp.outputs.python-path }}
        run: |
          just test-all --group "${{ matrix.mysqlclient-version }}" -p "$TEST_PYTHON" --group "$TEST_DJANGO_VERSION"
      - name: Store coverage files
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: ${{ env.COVERAGE_FILE }}
          path: ${{ env.COVERAGE_FILE }}

  oracle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    env:
      RDBMS: oracle
      TEST_PYTHON_VERSION: ${{ matrix.python-version }}
      TEST_DJANGO_VERSION: ${{ matrix.django-version }}
      TEST_DATABASE_VERSION: ${{ matrix.oracle-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.14']
        django-version:
          - 'dj42' # LTS April 2026
          - 'dj52' # LTS April 2028
          - 'dj60' #
        oracle-version:
          - 'oracle-xe:21'
          - 'oracle-free:latest'
        exclude:

          - django-version: 'dj42'
            oracle-version: 'oracle-free:latest'

          - django-version: 'dj52'
            oracle-version: 'oracle-free:latest'

          - django-version: 'dj60'
            oracle-version: 'oracle-xe:21'

          - python-version: '3.10'
            django-version: 'dj60'

          - python-version: '3.14'
            django-version: 'dj42'
          - python-version: '3.14'
            django-version: 'dj52'

    services:
      oracle1:
        image: gvenzl/${{ matrix.oracle-version }}  # zizmor: ignore[unpinned-images]
        env:
          ORACLE_PASSWORD: password
          ORACLE_DATABASE: test1
        # Forward Oracle port
        ports:
          - 1521:1521
        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

      oracle2:
        image: gvenzl/${{ matrix.oracle-version }}  # zizmor: ignore[unpinned-images]
        env:
          ORACLE_PASSWORD: password
          ORACLE_DATABASE: test2
        # Forward Oracle port
        ports:
          - 1522:1521
        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Set coverage file
        run: |
          ORACLE_TAG=$(echo "${{ matrix.oracle-version }}" | cut -d':' -f2)
          echo "COVERAGE_FILE=linux-py${{ matrix.python-version }}-${{ matrix.django-version }}-oracle${ORACLE_TAG}.coverage" >> $GITHUB_ENV
      - name: Clear Tool cache
        if: ${{ github.event.inputs.clear_cache == 'true' }}
        run: sudo rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        id: sp
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install Emacs
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          sudo apt install emacs
      - name: Setup tmate session
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101
        timeout-minutes: 60
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098
        with:
          enable-cache: false
      - name: Setup Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b
      - name: Install Oracle Client
        # https://askubuntu.com/questions/1512196/libaio1-on-noble
        run: |
          sudo apt install alien libaio1t64
          sudo ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1
          if [[ "${{ matrix.oracle-version }}" == oracle-xe* ]]; then
            curl --output oracle-client.rpm https://download.oracle.com/otn_software/linux/instantclient/2116000/oracle-instantclient-basiclite-21.16.0.0.0-1.el8.x86_64.rpm
            sudo alien -i oracle-client.rpm
            sudo sh -c "echo /usr/lib/oracle/21/client64/lib/ > /etc/ld.so.conf.d/oracle.conf"
          else
            curl --output oracle-client.rpm https://download.oracle.com/otn_software/linux/instantclient/2326000/oracle-instantclient-basiclite-23.26.0.0.0-1.el9.x86_64.rpm
            sudo alien -i oracle-client.rpm
            sudo sh -c "echo /usr/lib/oracle/23/client64/lib/ > /etc/ld.so.conf.d/oracle.conf"
          fi
          sudo ldconfig
      # we don't run integration tests against Oracle in CI, these are slow enough
      - name: Run Full Unit Tests
        env:
          TEST_PYTHON: ${{ steps.sp.outputs.python-path }}
        run: |
          if [[ "${{ matrix.oracle-version }}" == oracle-xe* ]]; then
            just test-all --group cx_oracle -p "$TEST_PYTHON" --group "$TEST_DJANGO_VERSION"
          else
            just test-all --group oracledb -p "$TEST_PYTHON" --group "$TEST_DJANGO_VERSION"
          fi

      - name: Store coverage files
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: ${{ env.COVERAGE_FILE }}
          path: ${{ env.COVERAGE_FILE }}


  windows:
    runs-on: windows-latest
    permissions:
      contents: read
      actions: write
    env:
      RDBMS: sqlite
      COVERAGE_FILE: windows-py${{ matrix.python-version }}-${{ matrix.django-version }}-sqlite.coverage
      TEST_PYTHON_VERSION: ${{ matrix.python-version }}
      TEST_DJANGO_VERSION: ${{ matrix.django-version }}
      TEST_DATABASE_VERSION: "sqlite"
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12', '3.14']
        django-version:
          - 'dj42' # LTS April 2026
          - 'dj52' # LTS April 2028
          - 'dj60' #
        exclude:
          - python-version: '3.10'
            django-version: 'dj52'
          - python-version: '3.10'
            django-version: 'dj60'

          - python-version: '3.12'
            django-version: 'dj42'
          - python-version: '3.12'
            django-version: 'dj60'

          - python-version: '3.14'
            django-version: 'dj42'
          - python-version: '3.14'
            django-version: 'dj52'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        id: sp
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098
        with:
          enable-cache: false
      - name: Setup Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b
      - name: install-vim-windows
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: rhysd/action-setup-vim@19e3dd31a84dbc2c5445d65e9b363f616cab96c1
      - name: Setup tmate session
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101
        timeout-minutes: 60
      - name: Run Unit Tests
        env:
          TEST_PYTHON: ${{ steps.sp.outputs.python-path }}
        run: |
          just test-all -p "$env:TEST_PYTHON" --group "$env:TEST_DJANGO_VERSION"
        shell: pwsh
      - name: Store coverage files
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: ${{ env.COVERAGE_FILE }}
          path: ${{ env.COVERAGE_FILE }}


  macos:
    runs-on: macos-latest
    permissions:
      contents: read
      actions: write
    env:
      RDBMS: sqlite
      COVERAGE_FILE: macos-py${{ matrix.python-version }}-${{ matrix.django-version }}-sqlite.coverage
      TEST_PYTHON_VERSION: ${{ matrix.python-version }}
      TEST_DJANGO_VERSION: ${{ matrix.django-version }}
      TEST_DATABASE_VERSION: "sqlite"
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12', '3.14']
        django-version:
          - 'dj42' # LTS April 2024
          - 'dj52' # LTS April 2028
          - 'dj60' #
        exclude:
          - python-version: '3.10'
            django-version: 'dj52'
          - python-version: '3.10'
            django-version: 'dj60'

          - python-version: '3.12'
            django-version: 'dj42'
          - python-version: '3.12'
            django-version: 'dj60'

          - python-version: '3.14'
            django-version: 'dj42'
          - python-version: '3.14'
            django-version: 'dj52'

    steps:
      - name: Clear Tool cache
        if: ${{ github.event.inputs.clear_cache == 'true' }}
        run: sudo rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        id: sp
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098
        with:
          enable-cache: false
      - name: Setup Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b
      - name: install-emacs-macos
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          brew install emacs
      - name: Setup tmate session
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101
        timeout-minutes: 60
      - name: Run Unit Tests
        env:
          TEST_PYTHON: ${{ steps.sp.outputs.python-path }}
        run: |
          just test-all -p "$TEST_PYTHON" --group "$TEST_DJANGO_VERSION"
      - name: Store coverage files
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: ${{ env.COVERAGE_FILE }}
          path: ${{ env.COVERAGE_FILE }}


  coverage-combine:
    needs: [postgres, sqlite, mysql, mariadb, oracle, windows, macos]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        id: sp
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098
        with:
          enable-cache: false
      - name: Setup Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b
      - name: Get coverage files
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3
        with:
          pattern: "*.coverage"
          merge-multiple: true
      - run: ls -la *.coverage
      - run: just coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files:
            ./coverage.xml
