name: Update Code of Conduct

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  # Run every Sunday at midnight UTC (00:00) - triggered by webhook?
  schedule:
    - cron: '0 0 * * SUN'


jobs:
  update_code_of_conduct:
    name: Update Code of Conduct
    permissions:
     contents: write  # allow updating the CODE_OF_CONDUCT.md file
     pull-requests: write  # needed for CoC PR

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Fetch CODE_OF_CONDUCT.md from django-commons
        run: |
          curl -o fetched_code_of_conduct.md https://raw.githubusercontent.com/django-commons/membership/main/CODE_OF_CONDUCT.md

      - name: Check if CODE_OF_CONDUCT.md has changed
        id: check_changes
        run: |
          if cmp -s fetched_code_of_conduct.md CODE_OF_CONDUCT.md; then
            echo "No changes in CODE_OF_CONDUCT.md"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "CODE_OF_CONDUCT.md has changed"
            echo "changed=true" >> $GITHUB_OUTPUT
            cp fetched_code_of_conduct.md CODE_OF_CONDUCT.md
          fi

      # Create a pull request to merge the changes into the main branch
      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
          BRANCH: update-coc
          REF_NAME: ${{ github.ref_name }}
          GH_ACTOR: ${{ github.actor }}
          GH_ACTOR_ID: ${{ github.actor_id }}
        run: |
          git config user.name "$GH_ACTOR"
          git config user.email "$GH_ACTOR_ID+$GH_ACTOR@users.noreply.github.com"

          git checkout -B "$BRANCH"
          git add CODE_OF_CONDUCT.md
          git commit -m "Update Code of Conduct"
          git push --force-with-lease origin "$BRANCH"

          gh pr view "$BRANCH" >/dev/null 2>&1 || gh pr create \
            --base "$REF_NAME" \
            --head "$BRANCH" \
            --title "Update Code of Conduct" \
            --body "Automated update."
