from .utils import add_media as add_media
from _typeshed import Incomplete
from django.forms.models import BaseInlineFormSet, BaseModelFormSet
from django.utils.functional import cached_property as cached_property
from polymorphic.models import PolymorphicModel as PolymorphicModel

class UnsupportedChildType(LookupError): ...

class PolymorphicFormSetChild:
    model: Incomplete
    fields: Incomplete
    exclude: Incomplete
    formfield_callback: Incomplete
    widgets: Incomplete
    localized_fields: Incomplete
    labels: Incomplete
    help_texts: Incomplete
    error_messages: Incomplete
    def __init__(self, model, form=..., fields=None, exclude=None, formfield_callback=None, widgets=None, localized_fields=None, labels=None, help_texts=None, error_messages=None) -> None: ...
    @cached_property
    def content_type(self): ...
    def get_form(self, **kwargs): ...

def polymorphic_child_forms_factory(formset_children, **kwargs): ...

class BasePolymorphicModelFormSet(BaseModelFormSet):
    child_forms: Incomplete
    queryset_data: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def add_fields(self, form, index) -> None: ...
    def get_form_class(self, model): ...
    def is_multipart(self): ...
    @property
    def media(self): ...
    @cached_property
    def empty_forms(self): ...
    @property
    def empty_form(self) -> None: ...

def polymorphic_modelformset_factory(model, formset_children, formset=..., form=..., fields=None, exclude=None, extra: int = 1, can_order: bool = False, can_delete: bool = True, max_num=None, formfield_callback=None, widgets=None, validate_max: bool = False, localized_fields=None, labels=None, help_texts=None, error_messages=None, min_num=None, validate_min: bool = False, field_classes=None, child_form_kwargs=None): ...

class BasePolymorphicInlineFormSet(BaseInlineFormSet, BasePolymorphicModelFormSet): ...

def polymorphic_inlineformset_factory(parent_model, model, formset_children, formset=..., fk_name=None, form=..., fields=None, exclude=None, extra: int = 1, can_order: bool = False, can_delete: bool = True, max_num=None, formfield_callback=None, widgets=None, validate_max: bool = False, localized_fields=None, labels=None, help_texts=None, error_messages=None, min_num=None, validate_min: bool = False, field_classes=None, child_form_kwargs=None): ...
